### ISSUE TITLE
make generators: `KeyError: 'error_code'`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-autonomy#1416]
after running `autonomy packages sync --update-packages` running `make generators` leads to the following failure

```
Updating packages/valory/connections/p2p_libp2p_client/__init__.py
Traceback (most recent call last):
  File "/home/zarathustra/Repositories/valory/open-autonomy/scripts/check_copyright.py", line 353, in <module>
    main()
  File "/home/zarathustra/Repositories/valory/open-autonomy/scripts/check_copyright.py", line 349, in main
    update_headers(python_files_filtered)
  File "/home/zarathustra/Repositories/valory/open-autonomy/scripts/check_copyright.py", line 242, in update_headers
    if not fix_header(check_data):
  File "/home/zarathustra/Repositories/valory/open-autonomy/scripts/check_copyright.py", line 198, in fix_header
    if check_info["error_code"] in (
KeyError: 'error_code'
```

which can be locally avoided by changing to `check_info.get("error_code")` but needs to be properly addressed

**Comment by Karrenbelt** [comment]
this occurs on modules with empty `__init__.py` files

**Comment by angrybayblade** [comment]
https://github.com/valory-xyz/open-autonomy/pull/1411#discussion_r991819340
