### ISSUE TITLE
most_voted_randomness should be a string

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-autonomy#1841]
While running an e2e test in the IEKit repo, I found an issue with how most_voted_randomness is treated. Basically, it is an int that is being converted to a base16 int, effectively executing the following code that raises:

```
>>> int(2716156, base=16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() can't convert non-string with explicit base
```

This seems to work, so I guess the value should be a string:
```
>>> int("2716156", base=16)
40984918
```

Which is confirmed by the definition at the abstract round:
```
    @property
    def most_voted_randomness(self) -> str:
        """Get the most_voted_randomness."""
        return cast(str, self.db.get_strict("most_voted_randomness"))
```

But during the execution:
`"most_voted_randomness": [2716156`]

Full stack trace:
```
[515781]stdout>[2023-02-20 18:55:31,475] [INFO] [agent_00001] Entered in the 'select_keeper_ceramic_behaviour' behaviour
[515781]stdout>[2023-02-20 18:55:31,476] [ERROR] [agent_00001] <An error occurred during act of behaviour valory/impact_evaluator_abci:0.1.0/ImpactEvaluatorConsensusBehaviour:
[515781]stdout>Traceback (most recent call last):
[515781]stdout>
[515781]stdout>  File "/tmp/tmpxyz0wbmx/agent_00001/vendor/valory/skills/abstract_round_abci/base.py", line 842, in keeper_randomness
[515781]stdout>    int(self.most_voted_randomness, base=16) / MAX_INT_256
[515781]stdout>
[515781]stdout>TypeError: int() can't convert non-string with explicit base
[515781]stdout>
[515781]stdout>
[515781]stdout>During handling of the above exception, another exception occurred:
[515781]stdout>
[515781]stdout>
[515781]stdout>Traceback (most recent call last):
[515781]stdout>
[515781]stdout>  File "/home/david/.local/share/virtualenvs/IEKit-5u0udIps/lib/python3.10/site-packages/aea/skills/base.py", line 440, in act_wrapper
[515781]stdout>    raise AEAActException(
[515781]stdout>
[515781]stdout>aea.exceptions.AEAActException: An error occurred during act of behaviour valory/impact_evaluator_abci:0.1.0/SelectKeeperCeramicBehaviour:
[515781]stdout>Traceback (most recent call last):
[515781]stdout>
[515781]stdout>  File "/tmp/tmpxyz0wbmx/agent_00001/vendor/valory/skills/abstract_round_abci/base.py", line 842, in keeper_randomness
[515781]stdout>    int(self.most_voted_randomness, base=16) / MAX_INT_256
[515781]stdout>
[515781]stdout>TypeError: int() can't convert non-string with explicit base
```

**Comment by Adamantios** [comment]
I believe this is not an issue in the `open-autonomy`, please check https://github.com/valory-xyz/IEKit/pull/17#pullrequestreview-1306818062.

**Comment by dvilelaf** [comment]
It is not an issue indeed, but a [problem](https://github.com/valory-xyz/IEKit/pull/17/commits/1de2ade3a36cb5a8b37fb7924aff9198031132ac) on my side with selection_key. I wonder why it was not failing before.
