### ISSUE TITLE
Default docker is not correct 

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#1969]
### Subject of the issue

incorrect version of docker is installed with the open-autonomy framewoek.

We are using 6.0.0

We should be using 6.1.2

errors with;
```
 I (mech-py3.10) ❰tom❙~/Desktop/Fun/hackathons/mech/packages/eightballer/services/mech(git≠✱feat/wf-fixes)❱✘≻ autonomy build-image
Building image with agent: eightballer/mech:0.1.0:bafybeieylo6ev4w4p7ui7vr5lyenb2lb33mbyqr7xtq43vcihwu5ttn3a4

Traceback (most recent call last):
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/bin/autonomy", line 8, in <module>
    sys.exit(cli())
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/autonomy/cli/build_images.py", line 69, in build_image
    _build_image(
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/autonomy/deploy/image.py", line 62, in build_image
    docker_client = from_env()
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```
Yet, when we upgrade docker, it works;

```

 I (mech-py3.10) ❰tom❙~/Desktop/Fun/hackathons/mech/packages/eightballer/services/mech(git≠✱feat/wf-fixes)❱✘≻ pip install -U docker
Requirement already satisfied: docker in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (6.0.0)
Collecting docker
  Downloading docker-6.1.2-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.1/148.1 kB 7.4 MB/s eta 0:00:00
Requirement already satisfied: packaging>=14.0 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from docker) (23.1)
Requirement already satisfied: websocket-client>=0.32.0 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from docker) (0.59.0)
Requirement already satisfied: requests>=2.26.0 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from docker) (2.30.0)
Requirement already satisfied: urllib3>=1.26.0 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from docker) (2.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from requests>=2.26.0->docker) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from requests>=2.26.0->docker) (2023.5.7)
Requirement already satisfied: idna<4,>=2.5 in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from requests>=2.26.0->docker) (3.4)
Requirement already satisfied: six in /home/tom/.cache/pypoetry/virtualenvs/mech-4BFSVe7_-py3.10/lib/python3.10/site-packages (from websocket-client>=0.32.0->docker) (1.16.0)
Installing collected packages: docker
  Attempting uninstall: docker
    Found existing installation: docker 6.0.0
    Uninstalling docker-6.0.0:
      Successfully uninstalled docker-6.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-autonomy 0.10.4 requires docker==6.0.0, but you have docker 6.1.2 which is incompatible.
docker-compose 1.29.2 requires PyYAML<6,>=3.10, but you have pyyaml 6.0 which is incompatible.
Successfully installed docker-6.1.2

```

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by 8ball030** [comment]
I (mech-py3.10) ❰tom❙~/Desktop/Fun/hackathons/mech/packages/eightballer/services/mech(git≠✱feat/wf-fixes)❱✔≻ autonomy build-image
Building image with agent: eightballer/mech:0.1.0:bafybeieylo6ev4w4p7ui7vr5lyenb2lb33mbyqr7xtq43vcihwu5ttn3a4

[docker]Step 1/13 : ARG AUTONOMY_IMAGE_VERSION="latest"[docker]
[docker]Step 2/13 : ARG AUTONOMY_IMAGE_NAME="valory/open-autonomy"[docker]
