### ISSUE TITLE
Minting tools improvements

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#2058]
### Subject of the issue
autonomy service activate launches an exeption

```
export CUSTOM_CHAIN_RPC=<rpc>
export CUSTOM_CHAIN_ID=100
export CUSTOM_SERVICE_MANAGER_ADDRESS="0xE3607b00E75f6405248323A9417ff6b39B244b50"
export CUSTOM_SERVICE_REGISTRY_ADDRESS="0x9338b5153AE39BB89f50468E608eD9d764B755fD"
export CUSTOM_GNOSIS_SAFE_MULTISIG_ADDRESS="0x3C1fF68f5aa342D296d4DEe4Bb1cACCA912D95fE"
export CUSTOM_GNOSIS_SAFE_PROXY_FACTORY_ADDRESS="0x3C1fF68f5aa342D296d4DEe4Bb1cACCA912D95fE"
export CUSTOM_GNOSIS_SAFE_SAME_ADDRESS_MULTISIG_ADDRESS="0x3d77596beb0f130a4415df3D2D8232B3d3D31e44"
export CUSTOM_MULTISEND_ADDRESS="0x40A2aCCbd92BCA938b02010E17A5b8929b49130D"
autonomy service --use-custom-chain activate 88 --key operator_pkey.txt 
```

```
Traceback (most recent call last):
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/bin/autonomy", line 8, in <module>
    sys.exit(cli())
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/autonomy/cli/service.py", line 71, in _activate
    ServiceHelper(
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/autonomy/cli/helpers/chain.py", line 543, in check_is_service_token_secured
    self.token_secured = is_service_token_secured(
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/autonomy/chain/service.py", line 168, in is_service_token_secured
    registry_contracts.service_registry_token_utility.is_token_secured_service(
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/autonomy/chain/base.py", line 168, in service_registry_token_utility
    self._service_registry_token_utility = self.get_contract(
  File "/home/user1/.cache/pypoetry/virtualenvs/trader-I2NvlnQ5-py3.10/lib/python3.10/site-packages/autonomy/chain/base.py", line 96, in get_contract
    raise FileNotFoundError(
FileNotFoundError: Contract package valory/service_registry_token_utility:latest not found in the open-autonomy installation, please reinstall the package
```

When addressing this issue, verify that subsequent steps do not fail (register agent instances, and deploy service).

### Your environment
- OS: Ubuntu
- Python version: 3.10
- Package Version 0.12.1.post1 and 0.12.0

### Steps to reproduce
See above

### Expected behaviour
See above

### Actual behaviour
See above

**Comment by Adamantios** [comment]
Apart from the bug above, the minting tools can be further improved. Some suggestions are:

1. Verify on-chain environment variables before making txs on CLI tools. In fact, it would be better if we added a single argument for known chains instead of setting all these environment variables since we already know these, e.g., see [here](https://github.com/valory-xyz/open-autonomy/blob/dc3e505679f438ed144f4e2cbd9026b41440edc0/docs/advanced_reference/on_chain_addresses.md).
2. Check the state before updating mints, i.e., the state should be terminated.
