### ISSUE TITLE
Failed native token transfer when amount is larger than ZERO_ADDRESS balance

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#2286]
### Subject of the issue

When transferring native tokens through the method [_transfer_from_eoa](https://github.com/valory-xyz/olas-operate-app/blob/2b654f55631b1bf466107efbeb7041d39e5e537d/operate/wallet/master.py#L183) from Olas Operate (which uses Open AEA [ledger_api.get_transfer_transaction](https://github.com/valory-xyz/open-aea/blob/436e63e06551d3f31571b81d2db6249ae171b83b/aea/crypto/ledger_apis.py#L122) and Open Autonomy [TxSettler](https://github.com/valory-xyz/open-autonomy/blob/2870d06a6781bfcbf5fa1d5b4a55bad89b339728/autonomy/chain/tx.py#L80) under the hood) it fails when the ZERO_ADDRESS balance is less than the desired transfer amount, regardles whether the user wallet has actually enough balance. Obviously, the balance what matters is the balance of the user wallet, not the ZERO_ADDRESS balance.

```
Traceback (most recent call last):
  File "/home/user1/git/olas-operate-app/test9.py", line 81, in <module>
    main()
  File "/home/user1/git/olas-operate-app/test9.py", line 40, in main
    wallet.transfer(
  File "/home/user1/git/olas-operate-app/operate/wallet/master.py", line 299, in transfer
    return self._transfer_from_eoa(
  File "/home/user1/git/olas-operate-app/operate/wallet/master.py", line 222, in _transfer_from_eoa
    tx_helper.transact(lambda x: x, "", kwargs={})
  File "/home/user1/.cache/pypoetry/virtualenvs/olas-operate-middleware-CyKIHtqy-py3.10/lib/python3.10/site-packages/autonomy/chain/tx.py", line 194, in transact
    raise ChainInteractionError(error) from e
autonomy.chain.exceptions.ChainInteractionError: insufficient funds for gas * price + value: address 0x0000000000000000000000000000000000000000 have 9757545024473567599 want 14220000000000000000
```
### Your environment
- OS: Ubuntu
- Python version: Python 3.10.12
- Package Version: autonomy, version 0.16.1

### Steps to reproduce
The following script allows to replicate the issue thorugh Olas Operate (should be possible to replicate with Open Autonomy alone as well). Assumes an existing setup of .operate folder with a funded Master EOA on Base.

```
import os
from pathlib import Path

from operate.cli import OperateApp
from operate.operate_types import (
    Chain,
    LedgerType,
)
from operate.ledger.profiles import USDC

REPO_ROOT = Path(__file__).resolve().parent
OPERATE_HOME = REPO_ROOT / ".operate"

def main():
    """main"""
    operate = OperateApp(
        home=OPERATE_HOME,
    )
    operate.setup()

    if operate.user_account is None:
        print("There is no user account created.")
        return

    password = "12345"
    if not operate.user_account.is_valid(password=password):
        print("Invalid password")
        return

    operate.password = password
    wallet = operate.wallet_manager.load(ledger_type=LedgerType.ETHEREUM)

    print("TRANSFER NATIVE EOA")
    wallet.transfer(
        to="0x29797303C0903B8C73D1c730D64E8eA4Ee4Ad9C4",
        amount=9900000000000000000,  # It will fail if the balance set here is > balance of ZERO address.
        chain=Chain.BASE,
        from_safe=False
    )
    print("")
    print("FINISHED")

if __name__ == "__main__":
    main()
```

**Comment by Adamantios** [comment]
This was fixed in https://github.com/valory-xyz/open-aea/blob/v1.59.0/HISTORY.md?plain=1#L6, which version are you using?

**Comment by jmoreira-valory** [comment]
Fixed after bumping framework version.
